Feature/unit test
takahiro-okada/java-todoapp-backend pull request #18
Opened 2022-10-07 10:38 UTC by takahiro-okada

## issue
#6 結合テストを実施する

## 変更の概要
/todosへのGETメソッドを行ったときにテストを導入した。  

## なぜこの変更をするのか
* APIのGETのテスト未実装のため実装

## やったこと

* [x] ステータスコードが200が返却されるのかの確認
* [x] Todoの中身が一致しているかの確認

## 変更内容

テスト内容: Todoが全件取得したときにステータスコードが200であること
https://github.com/takahiro-okada/java-todoapp-backend/blob/67881c0becc3ff92f480aaf51e29a653e6a25939/src/test/java/integrationstest/TodoRestApiIntegration.java#L29-L38
![CleanShot 2022-10-07 at 19 29 38](https://user-images.githubusercontent.com/76928095/194534277-59552027-b106-4103-a676-d0fcc110542d.png)

テスト内容: 取得した全件のTodoの中身が一致していること
https://github.com/takahiro-okada/java-todoapp-backend/blob/67881c0becc3ff92f480aaf51e29a653e6a25939/src/test/java/integrationstest/TodoRestApiIntegration.java#L40-L69
![CleanShot 2022-10-07 at 19 29 17](https://user-images.githubusercontent.com/76928095/194534269-a283d6c6-c7ab-45ad-971f-c728d9274624.png)

2022-10-09 00:56 UTC, YudaiNoda3576 requested changes
コメントしています！
異常系のテストの追加もお願いします！

2022-10-09 00:56 UTC, YudaiNoda3576 commented on src/test/java/com/example/demo/repository/TodoMapperTest.java
> +  void 取得したTodoの中身が一致すること() {
（削除は不要です）
Controllerのテストでレスポンスの中身を検証しており、そちらで担保されているのでこちらのテストは
それほど重要では無いかもしれません！（カバレッジをあげることが目的の場合は必要ですが、基本的に工数はできるだけ削減したいため、効率的にテストを進めると言う観点で行くとcontrollerのレスポンスが意図したものであることが担保されていることが重要のため、そちらを重点的に行い、Mapperなどのテストは件数の検証程度でとどめても問題はないかなと個人的には思います！）

2022-10-09 00:56 UTC, YudaiNoda3576 commented on src/test/java/integrationstest/TodoRestApiIntegration.java
> +  @Sql(
こういった処理は@BeforeEachなどを使うと良いかと思います！

2022-10-09 00:56 UTC, YudaiNoda3576 commented on src/test/java/integrationstest/TodoRestApiIntegration.java
> +  void Todoが全件取得したときにステータスコードが200であること() throws Exception {
個人的にはステータスコードが200であることを検証するテストケースは分離する必要はないかなと思います！（ステータスコードが200かどうかはそれほど重要ではなく、重要なのはあくまでもレスポンスが意図したものになっているかどうかのため）

なので、下記のテストにステータスコードが200かどうかを含める検証を入れておけば十分かもしれません
下記のテストは正常にレスポンスが返ることが前提のため、ステータスコードは当然２００になっているため念の為的にステータスコードの検証もしておくと言うようなイメージが近いです！

2022-10-09 02:52 UTC, merged

2022-10-11 00:49 UTC, takahiro-okada commented on src/test/java/integrationstest/TodoRestApiIntegration.java
> +  void Todoが全件取得したときにステータスコードが200であること() throws Exception {
@YudaiNoda3576 
ご返信ありがとうございます！
このあたり実際にどこまでテストをしていくのかがイメージがわかなかったのでとても参考になりました。
もう少しテストを自分で組んでいって、必要・不必要の判断ができるようになっていければと思います。

一旦今は学習用というところで残しておきます！